import type { StaffRole } from "@/lib/auth";

/**
 * Personalized login codes for staff — one per employee, prefixed by their
 * department so the code itself identifies who issued it, matching the
 * scheme you described: every department gets a fixed letter, followed by
 * a randomized suffix unique to that person.
 *
 * This is the *scheme*, not a real user-management system — there's no
 * database of individual employees yet, just one demo code per role (see
 * DEMO_USERS in lib/auth.ts). For real use, each of your 15+ Marketing
 * staff (etc.) would get their own row in a real users table, each with
 * their own code generated by generateUserCode() below at account-creation
 * time.
 */

export const ROLE_PREFIX: Record<StaffRole, string> = {
  system_admin: "S",
  administrative: "C", // "C" for CEO/Chief — Administrative is the CEO/Management seat
  manager: "G", // "G" for manaGer — "M" is already Marketing's
  admin: "A",
  marketing: "M",
  promotions: "P",
  promoter: "R", // "R" — Promoter's own code, distinct from Promotions' "P"
};

// Excludes 0/O and 1/I so codes are never ambiguous when read aloud or
// copied by hand.
const CODE_CHARS = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789";

export function generateUserCode(role: StaffRole): string {
  let suffix = "";
  for (let i = 0; i < 4; i++) {
    suffix += CODE_CHARS[Math.floor(Math.random() * CODE_CHARS.length)];
  }
  return `${ROLE_PREFIX[role]}-${suffix}`;
}

// Parses a code's prefix back to a role, so the login form can give a
// useful error ("that looks like a Marketing code, but no account matches
// it") without needing to search every role.
export function roleForPrefix(prefix: string): StaffRole | undefined {
  const entry = Object.entries(ROLE_PREFIX).find(([, p]) => p === prefix.toUpperCase());
  return entry?.[0] as StaffRole | undefined;
}
